export let wordsCategory = [
{word:'OKRĘT',category:'Rzecz',game:true},
{word:'PŁOZA',category:'Rzecz',game:true},
{word:'ŚWIAT',category:'Miejsce',game:true},
{word:'KALKA',category:'Rzecz',game:true},
{word:'GLINA',category:'Rzecz',game:true},
{word:'TARKA',category:'Rzecz',game:true},
{word:'PALMA',category:'Rośliny',game:true},
{word:'KIOSK',category:'Miejsce',game:true},
{word:'RYBAK',category:'Osoba',game:true},
{word:'PASAŻ',category:'Miejsce',game:true},
{word:'SERCE',category:'Rzecz',game:true},
{word:'PULPA',category:'Rzecz',game:true},
{word:'KREDA',category:'Rzecz',game:true},
]
